// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://priqcoqsqrrvsdudhpgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByaXFjb3FzcXJydnNkdWRocGdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NTcxMTQsImV4cCI6MjA1OTQzMzExNH0.x-4eaR2TrWPdJiWcoIdvy0baUKVGAef25dtEvETB79c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);